on: push

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Export
      uses: firebelley/godot-export@v2
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.2/mono/Godot_v3.2.2-stable_mono_linux_headless_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.2/mono/Godot_v3.2.2stable_mono_export_templates.tpz
        relative_project_path: ./
        create_release: false
    - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: http/
          TARGET_FOLDER: master/game/
          CLEAN: true
